### ISSUE TITLE
Could not find module

### ISSUE THREAD

**Issue by LengerHu** [xxh0523/FCDRL_TSCOPF#1]
Traceback (most recent call last):
  File "sopf_base.py", line 251, in <module>
    env = sopf_optimum_Env(
  File "C:\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\env_SOPF_Optimum.py", line 65, in __init__
    self.psops = Py_PSOPS(flg=self.flg, rng=rng)
  File "C:\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\psops\py_psops.py", line 61, in __init__
    self._load_dll(dll_path)
  File "C:\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\psops\py_psops.py", line 102, in _load_dll
    self.__psDLL = cdll.LoadLibrary(dll_path)
  File "D:\ProgramData\anaconda3\envs\RL\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "D:\ProgramData\anaconda3\envs\RL\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\psops\dll_win\PSOPS_Source.dll' (or one of its dependencies). Try using the full path with constructor syntax.
api for psops deletion successful.

By instanly input  ---> python sopf_base.py --training, it returns the message
The environment is Win11, Python 3.9
qtwebkit has installed in the environment.

**Comment by xxh0523** [comment]
Everything works fine with me. 

Did you fetch the full repository?

Or you can download the DLL file here.....
https://github.com/xxh0523/FCDRL_TSCOPF/blob/main/gym_psops/envs/psops/dll_win/PSOPS_Source.dll

**Comment by LengerHu** [comment]
Thanks for your advice！It works. Could you please tell me if I want to add the solar panel or wind turbine , how to add them in the IEEE39 sample  and whether the [Py_PSOPS](https://github.com/xxh0523/Py_PSOPS) can handle the process of  simulation or not?  I notice that there is a IEEE39 origin sample in the samples document. But if I change the sample to  a new DAT file (solar panel or wind turbine added) , can Py_PSOPS be used for simulation to handle the TSCOPF problem?

**Comment by xxh0523** [comment]
> Thanks for your advice！It works. Could you please tell me if I want to add the solar panel or wind turbine , how to add them in the IEEE39 sample and whether the [Py_PSOPS](https://github.com/xxh0523/Py_PSOPS) can handle the process of simulation or not? I notice that there is a IEEE39 origin sample in the samples document. But if I change the sample to a new DAT file (solar panel or wind turbine added) , can Py_PSOPS be used for simulation to handle the TSCOPF problem?

Sorry for the late reply. Py_PSOPS supports the type-1 solar model of PSASP but currently does NOT support wind turbine models. 

Are you from China? You can contact me on WeChat (ee_xtn).

**Comment by Flygpu** [comment]
> 回溯（最近一次调用）：文件 “sopf_base.py”，第 251 行，在 env = sopf_optimum_Env（ 文件 “C：\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\env_SOPF_Optimum.py”，第 65 行，**在 init** self.psops = Py_PSOPS（flg=self.flg， rng=rng） 文件 “C：\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\psops\py_psops.py”，第 61 行，在 **init** self._load_dll（dll_path） 中文件“C：\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\psops\py_psops.py”，第 102 行，_load_dll _self._psDLL = cdll.LoadLibrary（dll_path）文件“D：\ProgramData\anaconda3\envs\RL\lib\ctypes__init__.py”，第 451 行，在 LoadLibrary 中返回 self。_dlltype（name） 文件 “D：\ProgramData\anaconda3\envs\RL\lib\ctypes__init__.py”，第 373 行，**init** self._handle = _dlopen（self._name， mode） FileNotFoundError：找不到模块 'C：\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\psops\dll_win\PSOPS_Source.dll' （或其依赖项之一）。尝试将完整路径与 constructor 语法一起使用。用于 PSOPS 的 API 删除成功。
> 
> 通过直接输入 python sopf_base.py --training --->，返回消息 The environment is Win11， Python 3.9 qtwebkit has installed in the environment.

I also encountered the same problem, could you please tell me how you solved it?

**Comment by Qiu-Belfast** [comment]
> > 回溯（最近一次调用）：文件 “sopf_base.py”，第 251 行，在 env = sopf_optimum_Env（ 文件 “C：\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\env_SOPF_Optimum.py”，第 65 行，**在 init** self.psops = Py_PSOPS（flg=self.flg， rng=rng） 文件 “C：\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\psops\py_psops.py”，第 61 行，在 **init** self._load_dll（dll_path） 中文件“C：\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\psops\py_psops.py”，第 102 行，_load_dll _self._psDLL = cdll.LoadLibrary（dll_path）文件“D：\ProgramData\anaconda3\envs\RL\lib\ctypes__init__.py”，第 451 行，在 LoadLibrary 中返回 self。_dlltype（name） 文件 “D：\ProgramData\anaconda3\envs\RL\lib\ctypes__init__.py”，第 373 行，**init** self._handle = _dlopen（self._name， mode） FileNotFoundError：找不到模块 'C：\Users\hulia\Desktop\FCDRL_TSCOPF-main\gym_psops\envs\psops\dll_win\PSOPS_Source.dll' （或其依赖项之一）。尝试将完整路径与 constructor 语法一起使用。用于 PSOPS 的 API 删除成功。
> > 通过直接输入 python sopf_base.py --training --->，返回消息 The environment is Win11， Python 3.9 qtwebkit has installed in the environment.
> 
> I also encountered the same problem, could you please tell me how you solved it?

中文：很抱歉这么晚回复，我今天也遇到了这个问题。解决该问题，你需要输入conda install qtwebkit这行代码在你的Conda环境，详细信息见博主的另一个仓库https://github.com/xxh0523/Py_PSOPS

English:I'm very sorry for replying so late. I also encountered this problem today. To solve this problem, you need to enter conda install qtwebkit this line of code in your conda environment, details see another project https://github.com/xxh0523/Py_PSOPS warehouse
